import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Warbot Scouting",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-black text-white antialiased">
        {/* --- NAVIGATION BAR --- */}
        <nav className="sticky top-0 z-50 bg-black/80 backdrop-blur-md border-b border-gray-800">
          <div className="max-w-6xl mx-auto px-6 h-16 flex items-center justify-between">
            <Link href="/" className="text-xl font-black tracking-tighter text-red-500">
              Warbot Scouting: REBUILT
            </Link>
            
            <div className="flex gap-6 text-sm font-bold uppercase tracking-wide text-gray-400">
              <Link href="/scout" className="hover:text-white transition">Scout</Link>
              <Link href="/pitscout" className="hover:text-white transition">Pit Scouting</Link>
              <Link href="/analysis/matches" className="hover:text-white transition">Match Analysis</Link>
              <Link href="/analysis/teams" className="hover:text-white transition">Team Analysis</Link>

              <Link href="/admin" className="hover:text-gray-200 text-gray-600 transition">Admin</Link>
            </div>
          </div>
        </nav>

        {/* --- PAGE CONTENT --- */}
        <main>{children}</main>
      </body>
    </html>
  );
}
