import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Warbot Scouting",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-black text-white antialiased flex flex-col min-h-screen">
        {/* --- NAVIGATION BAR --- */}
<nav className="sticky top-0 z-50 bg-black/90 backdrop-blur-md border-b border-gray-800">
  <div className="max-w-6xl mx-auto px-4 py-3 flex flex-col sm:flex-row items-center justify-between gap-4">
    <Link href="/" className="text-xl font-black tracking-tighter text-red-500 text-center sm:text-left">
      Warbot Scouting
    </Link>
    
    {/* Use overflow-x-auto so users can swipe through links on small phones */}
    <div className="flex gap-4 text-[15px] font-bold uppercase tracking-wider text-gray-400 overflow-x-auto w-full sm:w-auto justify-center sm:justify-end pb-1 no-scrollbar">
      <Link href="/scout" className="hover:text-white whitespace-nowrap">Scout</Link>
      <Link href="/pitscout" className="hover:text-white whitespace-nowrap">Pit</Link>
      <Link href="/analysis/matches" className="hover:text-white whitespace-nowrap">Matches</Link>
      <Link href="/analysis/teams" className="hover:text-white whitespace-nowrap">Teams</Link>
      <Link href="/analysis/pick-lists" className="hover:text-white whitespace-nowrap">Picks</Link>
      {/*<Link href="/admin" className="hover:text-gray whitespace-nowrap">Admin</Link>*/}
    </div>
  </div>
</nav>

        {/* --- PAGE CONTENT --- */}
        <main className="flex-grow">
          {children}
          </main>
        <footer className="border-t border-gray-900 bg-black/50 py-8 mt-10">
          <div className="max-w-7xl mx-auto px-6 flex flex-col md:flex-row items-center justify-between gap-4">
            
            <div className="text-center md:text-left">
              <p className="text-[10px] font-black text-gray-600 uppercase tracking-[0.3em]">
                Warbot Scouting // REBUILT
              </p>
            </div>

            <a 
              href="https://www.thebluealliance.com/" 
              target="_blank" 
              rel="noopener noreferrer"
              className="flex items-center gap-2 grayscale opacity-50 hover:opacity-100 hover:grayscale-0 transition-all"
            >
              <span className="text-[10px] font-bold text-gray-500 uppercase">Powered by</span>
              <span className="text-xs font-black italic tracking-tighter text-blue-500">
              The Blue Alliance
              </span>
            </a>

          </div>
        </footer>
      </body>
    </html>
  );
}
